### ISSUE TITLE
error: ETIMEDOUT during code sending

### ISSUE THREAD

**Issue by MIkhailVrn** [zerobias/telegram-mtproto#112]
Hi,

I am trying to send the code for authorization but it is just freezing for about a 30 second and then returns "ETIMEDOUT". I already tried a lot of different settings and configurations. Last one is:

```
var MTProto = require("telegram-mtproto").MTProto;

var number = "+795******";
console.log("Calling auth.sendCode on number=" + number);

var APP = {
    id:      ******,
    hash:    "***",
    version: "0.0.1",
    lang:    "en",
};

var client = MTProto({
    api: {
        layer:       57,
        api_id:      APP.id,
        app_version: APP.version,
        lang_code:   APP.lang,
    },
    server: {
        webogram: true,
        dev:      false,
    },
});

client("auth.sendCode", {
    phone_number:   number,
    current_number: false,
    //sms_type:       5,
    api_id:         APP.id,
    api_hash:       APP.hash,
}).then((result) => {
    console.log("sendCode succeeded:", result);
    process.exit(0);
});

```

this is the error, which i get:
```
[132.001] req_pq error connect ETIMEDOUT 149.154.175.115:443
Get networker error { Error: connect ETIMEDOUT 149.154.175.115:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '149.154.175.115',
  port: 443,
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: { 'User-Agent': 'axios/0.15.3', 'Content-Length': 40 },
     method: 'post',
     responseType: 'arraybuffer',
     url: 'https://aurora.web.telegram.org/apiw1',
     data: ArrayBuffer { byteLength: 40 } },
  response: undefined } Error: connect ETIMEDOUT 149.154.175.115:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
Unhandled rejection Error: connect ETIMEDOUT 149.154.175.115:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

Unhandled rejection Error: connect ETIMEDOUT 149.154.175.115:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)


```

Did somebody get this issue as well? I just can't get what is wrong... 
Or maybe you have some ideas how to solve it.

Thanks in advance

**Comment by 2012mjm** [comment]
which version are you using?
