### ISSUE TITLE
TypeError: No session! folktale:Maybe.Nothing

### ISSUE THREAD

**Issue by agogex** [zerobias/telegram-mtproto#115]
When i try invoke client with 'auth.sendCode' i get this exception:
```
Exception has occurred: TypeError
TypeError: No session! folktale:Maybe.Nothing({  })
    at ChainAction.makeApiBytes [as mapper] (e:\dev\xelentec\dating-bot\node_modules\telegram-mtproto\src\state\epic\net-request.js:33:11)
    at ChainAction$resolved [as resolved] (e:\dev\xelentec\dating-bot\node_modules\fluture\index.js:798:27)
    at Timeout.resolved [as _onTimeout] (e:\dev\xelentec\dating-bot\node_modules\fluture\index.js:213:19)
    at ontimeout (timers.js:475:15)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)
```
And in console next message: 
```javascript
{
_:"rpc_error"
error_code:500
error_message:"AUTH_RESTART"
}
```

**Comment by goodmind** [comment]
Do you use storage-fs?

**Comment by agogex** [comment]
Yes, I do.
```javascript
const { Storage } = require('mtproto-storage-fs');
...
const app = {
      storage: new Storage(`./path/to/storage.json`)
    };
```
