### ISSUE TITLE
Encrypted request failed { Error: MT[406] NETWORK_BAD_REQUEST

### ISSUE THREAD

**Issue by marcelo-mason** [zerobias/telegram-mtproto#131]
Every once in a while I get errors like these which crash my app.  Where can I catch these?

```
Encrypted request failed { Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.175.50/apiw1
    at NetworkerThread._ref20 (d:\Projects\SignalsSociety\node_modules\telegram-mtproto\lib\service\networker\index.js:1050:40)
    at _ref20.throw (<anonymous>)
    at step (d:\Projects\SignalsSociety\node_modules\telegram-mtproto\lib\service\networker\index.js:62:202)
    at d:\Projects\SignalsSociety\node_modules\telegram-mtproto\lib\service\networker\index.js:62:424
    at tryCatcher (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
  code: 406,
  type: 'NETWORK_BAD_REQUEST',
  originalError:
   { Error: read ECONNRESET
    at _errnoException (util.js:1019:11)
    at TCP.onread (net.js:608:25)
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read',
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        responseType: 'arraybuffer',
        url: 'http://149.154.175.50/apiw1',
        data: ArrayBuffer { byteLength: 5256 } },
     response: undefined } }
Unhandled rejection Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.175.50/apiw1
    at NetworkerThread._ref20 (d:\Projects\SignalsSociety\node_modules\telegram-mtproto\lib\service\networker\index.js:1050:40)
    at _ref20.throw (<anonymous>)
    at step (d:\Projects\SignalsSociety\node_modules\telegram-mtproto\lib\service\networker\index.js:62:202)
    at d:\Projects\SignalsSociety\node_modules\telegram-mtproto\lib\service\networker\index.js:62:424
    at tryCatcher (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (d:\Projects\SignalsSociety\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

Unhandled rejection undefined

Unhandled rejection undefined

Unhandled rejection undefined
```

**Comment by marcelo-mason** [comment]
Think this was a layer version mismatch.  Can ignore.

**Comment by vodniciarv** [comment]
in which version does not this error exist?

**Comment by KylinWu** [comment]
Hey @iceflash , try official client library [TDLib](https://github.com/tdlib/td).
Here is a awesome bindings for node.js [tdl](https://github.com/Bannerets/tdl) by @Bannerets.

**Comment by iceflash** [comment]
@KylinWu thx, i will take a look on it
