### ISSUE TITLE
TypeError: Future.encaseP expects its first argument to be a function

### ISSUE THREAD

**Issue by adplaygit** [zerobias/telegram-mtproto#146]
```
 var MTProto = require('telegram-mtproto').MTProto;
                    var Storage = require('mtproto-storage-fs').Storage;
                    var server = {
                        dev: false
                       

                    };


                    var api = {

                        layer: layer,
                        initConnection:  0x69796de9,
                        api_id: 123456),
                        lang_code: 'en',
                        app_version: '1.0.1',
                        invokeWithLayer: 0xda9b0d0d,
                        device_model: "PC",
                        system_version: "Windows",
                    };
                   
                    var appStorage = {
                        storage: new Storage("/telegramAuth/" + 'mystore.json')
                    };
                    var client = MTProto({server: server, api: api, app: appStorage});
client('help.getNearestDc', {}).then(function (config) {
                                        console.log('help.getNearestDc = ', JSON.stringify(config));
                                        

                                    });
```

and error = 

> 
> TypeError: Future.encaseP expects its first argument to be a function
> Actual: undefined
> at typeError (C:\node\node\node_modules\fluture\index.js:80:9)
> at invalidArgument (C:\node\node\node_modules\fluture\index.js:84:3)
> at encaseP (C:\node\node\node_modules\fluture\index.js:1810:22)
> at Object.<anonymous> (C:\node\node\node_modules\telegram-mtproto\lib\service\authorizer\index.js:86:36)
> at Module._compile (module.js:635:30)
> at Object.Module._extensions..js (module.js:646:10)
> at Module.load (module.js:554:32)
> at tryModuleLoad (module.js:497:12)
> at Function.Module._load (module.js:489:3)
> at Module.require (module.js:579:17)
> at require (internal/module.js:11:18)
> at Object.<anonymous> (C:\node\node\node_modules\telegram-mtproto\lib\service\invoke.js:15:19)
> at Module._compile (module.js:635:30)
> at Object.Module._extensions..js (module.js:646:10)
> at Module.load (module.js:554:32)
> at tryModuleLoad (module.js:497:12)
> at Function.Module._load (module.js:489:3)
> at Module.require (module.js:579:17)
> at require (internal/module.js:11:18)
> at Object.<anonymous> (C:\node\node\node_modules\telegram-mtproto\lib\service\main\wrap.js:16:15)
> at Module._compile (module.js:635:30)
> at Object.Module._extensions..js (module.js:646:10)
> at Module.load (module.js:554:32)
> at tryModuleLoad (module.js:497:12)
> at Function.Module._load (module.js:489:3)
> 

please help me @zerobias

**Comment by adplaygit** [comment]
i solve that
nothing important
thanks @zerobias   @goodmind
