### ISSUE TITLE
auth.signIn -- Unhandled rejection RangeError: Source is too large

### ISSUE THREAD

**Issue by GeorgeAnanthSoosai** [zerobias/telegram-mtproto#153]
During singin, I'm getting following error, 

**Code**
client('auth.signIn', {
            phone_number: "+14042475634",
            phone_code_hash: data.phoneCodeHash,
            phone_code: data.phoneCode
        }).then(function (signIn) {
            //console.log(signIn)
        })

**Error :**

Unhandled rejection RangeError: Source is too large
debuggability.js:868
    at Int32Array.set (native)
    at TypeWriter.checkLength (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/type-buffer.js:111:33)
    at Object.bytes (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/mediator.js:55:9)
    at Serialization.storeObject (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/index.js:190:40)
    at Serialization.storeMethod (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/index.js:141:19)
    at NetworkerThread.wrapApiCall (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/networker/index.js:222:37)
    at Request.requestWith.networker (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/request.js:37:47)
    at tryCatcher (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by GeorgeAnanthSoosai** [comment]
I'm sure, I'm missing anything. Please advise me on this

**Comment by GeorgeAnanthSoosai** [comment]
Can anyone help me on this ?

**Comment by zerobias** [comment]
Hi, which version are you using?

**Comment by GeorgeAnanthSoosai** [comment]
Thank you for quick response.. 

I'm using the version : "version": "2.2.2"

**Comment by GeorgeAnanthSoosai** [comment]
@zerobias - Is there any stable version that i can use for the same ? -- Please advise if any configuration i got missed!.

**Comment by GeorgeAnanthSoosai** [comment]
Looks like version is getting updated now : "2.2.8". Even then i got the issue

**Comment by GeorgeAnanthSoosai** [comment]
**[10.804] Error undefined undefined 2 1**
index.js:254
**Unhandled rejection RangeError: Source is too large**
debuggability.js:868
    at Int32Array.set (native)
    at TypeWriter.checkLength (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/type-buffer.js:111:33)
    at writeBytes (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/writer.js:61:7)
    at Serialization.storeObject (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/index.js:197:39)
    at Serialization.storeMethod (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/index.js:144:19)
    at NetworkerThread.wrapApiCall (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/networker/index.js:239:37)
    at Request.requestWith.networker (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/request.js:37:47)
    at <anonymous>

**Comment by zerobias** [comment]
I don't understand why I see Int32Array here, seems weird, library uses Uint8Array

By the way, you could try version 3.2.10

**Comment by GeorgeAnanthSoosai** [comment]
Any documentation for 3.2.10 ?

**Comment by GeorgeAnanthSoosai** [comment]
Now the API is hanging and no error. It is not triggering success/failure callback

**Comment by GeorgeAnanthSoosai** [comment]
Are you looking into this issue Sir ? please advise me to get into sigin in..

**Comment by GeorgeAnanthSoosai** [comment]
Can you please check the package.json to see any of the version got updated for those which has ^ prefix. it might be causing an issue.

**Comment by GeorgeAnanthSoosai** [comment]
Again,

If i try the following version 3.1.0, I was able to get auth code. But during sign in, it went through two steps and then error, 

REQUEST
stream-bus.js:61
AUTH
stream-bus.js:61
WORK
stream-bus.js:61
[8.147] Error undefined undefined 2 2
index.js:299
REQUEST
stream-bus.js:61
[8.155] Error undefined undefined 2 2
index.js:299

**Comment by GeorgeAnanthSoosai** [comment]
can you please give me one example for 3.2.10 version ?

**Comment by GeorgeAnanthSoosai** [comment]
CAN YOU PLEASE CHECK BELOW ISSEUE ? 


[8.428] Error undefined undefined 2 2
index.js:265
console.trace()
index.js:266
    at (anonymous) (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:288:16)
    at step (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:201)
    at (anonymous) (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:382)
    at tryCatcher (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/util.js:16:22)
    at Promise._settlePromiseFromHandler (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:512:30)
    at Promise._settlePromise (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:569:17)
    at Promise._settlePromiseCtx (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:606:9)
    at Async._drainQueue (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:138:11)
    at Async._drainQueues (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:143:9)
    at Async.drainQueues (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:17:13)
    at runCallback (timers.js:789:19)
    at tryOnImmediate (timers.js:751:4)
    at processImmediate (timers.js:722:4)
Trace: Unhandled performRequest
console.js:185
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/src/service/api-manager/index.js:266:15
    at Generator.next (<anonymous>)
    at step (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:202)
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:383
    at tryCatcher (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by GeorgeAnanthSoosai** [comment]
ALSO, 

[rejectPromise] Unhandled error!
index.js:281
RangeError: Source is too large
index.js:281
Unhandled rejection RangeError: Source is too large
debuggability.js:868
    at Int32Array.set (native)
    at TypeWriter.checkLength (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/type-buffer.js:111:33)
    at writeBytes (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/writer.js:61:7)
    at Serialization.storeObject (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/index.js:198:39)
    at Serialization.storeMethod (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/tl/index.js:145:19)
    at NetworkerThread.wrapApiCall (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/networker/index.js:435:37)
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:282:38
From previous event:
    at exports.blueDefer (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/util/defer.js:28:17)
    at new ApiRequest (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/main/request.js:25:34)
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:233:20
    at Generator.next (<anonymous>)
    at step (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:202)
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:383
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at step (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:359)
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:459
From previous event:
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:99
    at ApiManager.mtpInvokeApi (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/api-manager/index.js:253:7)
    at telegram (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/telegram-mtproto/lib/service/main/wrap.js:23:16)
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/server/components/TelegramController/telegramContoller.js:83:9
    at model.Query.<anonymous> (/Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/mongoose/lib/model.js:4074:16)
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/kareem/index.js:273:21
    at /Users/georgesoosai/Trading_Gdax/gdaxautomatetrading/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by GeorgeAnanthSoosai** [comment]
Would you able to recreate this issue ? 

Can you please me some insight on this ?

**Comment by GeorgeAnanthSoosai** [comment]
Any tips ?

**Comment by goodmind** [comment]
It's strange

**Comment by GeorgeAnanthSoosai** [comment]
Thank for helping.. 

Unfortunately i did not able to make it. It was not reaching to success/failure callback. Also, i got no error. Not sure if anything I've missed.. 


Below is the code for your referance, 

`var TelegramChannel = require("telegram-mtproto");`

`var apiObj = {
    layer: 57,
    initConnection: 0x69796de9,
    invokeWithLayer: 0xda9b0d0d,
    app_version: '1.0.1',
    api_id: 182342,
    lang_code: 'en'
}

const server = {
    webogram: true,
    dev: false,
    dcList : [{id : 182342, host : "149.154.167.50", port : 443}]
}`

`function generateAuthCode() {
    var deferred = q.defer();
    var client = TelegramChannel.MTProto({
        server,
        apiObj
    })

    client('auth.sendCode', {
        phone_number: "+14042475634",
        current_number: true,
        //phone_registered: true,
        api_id: 182342,
        //sms_type : 5,
        api_hash: '4aa42dc646b7701a9fc36fe22de7dd4b'
    }).then(
        function (user) {
            console.log(user);
            var telegramAuthModelObj = new TelegramAuthModel();
            telegramAuthModelObj.phoneCodeHash = user;
            telegramAuthModelObj.save(function (err) {
                if (!err) {
                    signIn();
                    return deferred.resolve();
                }
                return deferred.reject(err);
            })
        },
        function (err) {
            return deferred.reject(err);
        }
    )
    return deferred.promise;
}

function signIn() {
    var client = TelegramChannel.MTProto({
        server,
        apiObj
    })
    TelegramAuthModel.findOne({}, function (err, data) {
        var phoneCodeHash = data.phoneCodeHash;
        client('auth.signIn', {
            phone_number: "+14042475634",
            phoneCodeHash,
            phone_code: data.phoneCode
        }).then(function (signIn) {
            console.log(signIn)  // Not reaching here after version upgrade
        }, function (err) {
            console.log(err); // Not reaching here too after version upgrade(but old version was reaching here - failure callback)
        })
    })

}`

**Comment by OwnageIsMagic** [comment]
rename `apiObj` -> `api`, `phoneCodeHash` -> `phone_code_hash`
you doesn't have any code where you entering received `phone_code`
btw you should create only one instance of MTProto and reuse it
Here is working login example https://github.com/zerobias/telegram-mtproto/issues/117#issuecomment-343712398

**Comment by GeorgeAnanthSoosai** [comment]
I'm entering the phone code into the DB, 

```
/* 1 */
{
    "_id" : ObjectId("5a8a558d13612a11aee675f0"),
    "phoneCode" : 52117,
    "phoneCodeHash" : {
        "next_type" : {
            "_" : "auth.codeTypeSms"
        },
        "phone_code_hash" : "c20327da885052f772",
        "type" : {
            "length" : 5,
            "_" : "auth.sentCodeTypeApp"
        },
        "phone_registered" : true,
        "flags" : 3,
        "_" : "auth.sentCode"
    },
    "__v" : 0
}
```

Even the auth code is not generating from the new version change.. 

Here is what i've changed after your advsie, 
Can you please check and advise me where i'm doing wrong, 


```
var api = {
    layer: 57,
    initConnection: 0x69796de9,
    invokeWithLayer: 0xda9b0d0d,
    app_version: '1.0.1',
    api_id: 182342,
    lang_code: 'en'
}

const server = {
    webogram: true,
    dev: false,
    dcList : [{id : 182342, host : "149.154.167.50", port : 443}]
}



function generateAuthCode() {
    var deferred = q.defer();
    var client = TelegramChannel.MTProto({
        server : server,
        api : api
    })

    client('auth.sendCode', {
        phone_number: "+14042475634",
        current_number: true,
        //phone_registered: true,
        api_id: 182342,
        //sms_type : 5,
        api_hash: '4aa42dc646b7701a9fc36fe22de7dd4b'
    }).then(
        function (user) {
            console.log(user);
            var telegramAuthModelObj = new TelegramAuthModel();
            telegramAuthModelObj.phoneCodeHash = user;
            telegramAuthModelObj.save(function (err) {
                if (!err) {
                    signIn();
                    return deferred.resolve();
                }
                return deferred.reject(err);
            })
        },
        function (err) {
            return deferred.reject(err);
        }
    )
    return deferred.promise;
}

function signIn() {
    var client = TelegramChannel.MTProto({
        server : server,
        api : api
    })
    TelegramAuthModel.findOne({}, function (err, data) {
        var phoneCodeHash = data.phoneCodeHash;
        client('auth.signIn', {
            phone_number: "+14042475634",
            phone_code_hash: phoneCodeHash,
            phone_code: data.phoneCode
        }).then(function (signIn) {
            console.log(signIn)
        }, function (err) {
            console.log(err);
        })
    })

}
generateAuthCode();
```

**Comment by GeorgeAnanthSoosai** [comment]
@goodmind 
```
var client = TelegramChannel.MTProto({
        server,
        api
    })

```
Here is what i see when above code is executed, 

```
api:Object {invokeWithLayer: 3667594509, layer: 57, initConnection: 1769565673, …}
api_id:182342
app_version:"1.0.1"
device_model:"Unknown UserAgent"
initConnection:1769565673
invokeWithLayer:3667594509
lang_code:"en"
layer:57
system_version:"Unknown Platform"
```

**Comment by GeorgeAnanthSoosai** [comment]
Moved instance to the top, even still auth code is not generating now with the updated version, 

```
var TelegramChannel = require("telegram-mtproto");
var api = {
    layer: 57,
    initConnection: 0x69796de9,
    invokeWithLayer: 0xda9b0d0d,
    app_version: '1.0.1',
    api_id: 182342,
    lang_code: 'en'
}

const server = {
    webogram: true,
    dev: false,
    dcList : [{id : 182342, host : "149.154.167.50", port : 443}]
}

var client = TelegramChannel.MTProto({
    server,
    api
})

function generateAuthCode() {
    var deferred = q.defer();
    client('auth.sendCode', {
        phone_number: "+14042475634",
        current_number: true,
        //phone_registered: true,
        api_id: 182342,
        //sms_type : 5,
        api_hash: '4aa42dc646b7701a9fc36fe22de7dd4b'
    }).then(
        function (user) {
            console.log(user);
            var telegramAuthModelObj = new TelegramAuthModel();
            telegramAuthModelObj.phoneCodeHash = user;
            telegramAuthModelObj.save(function (err) {
                if (!err) {
                    signIn();
                    return deferred.resolve();
                }
                return deferred.reject(err);
            })
        },
        function (err) {
            return deferred.reject(err);
        }
    )
    return deferred.promise;
}

function signIn() {
    TelegramAuthModel.findOne({}, function (err, data) {
        var phoneCodeHash = data.phoneCodeHash;
        client('auth.signIn', {
            phone_number: "+14042475634",
            phone_code_hash: phoneCodeHash,
            phone_code: data.phoneCode
        }).then(function (signIn) {
            console.log(signIn)
        }, function (err) {
            console.log(err);
        })
    })

}
generateAuthCode();
```

**Comment by GeorgeAnanthSoosai** [comment]
I'm not sure exactly what I'm missing. There is no error. The client function got called and hanged..

**Comment by taurheim** [comment]
Having the same issue - is there any more information needed to help fix this?

**Comment by GeorgeAnanthSoosai** [comment]
Can anyone please give me the working example ?

**Comment by halipso** [comment]
I finally fixed it.
Make sure that all values are String.
I was sending code as integer and faced the same issue

**Comment by halipso** [comment]
`function signIn() {
    TelegramAuthModel.findOne({}, function (err, data) {
        var phoneCodeHash = data.phoneCodeHash;
        client('auth.signIn', {
            phone_number: "+14042475634",
            phone_code_hash: phoneCodeHash,
            phone_code: data.phoneCode.**toString()**
        }).then(function (signIn) {
            console.log(signIn)
        }, function (err) {
            console.log(err);
        })
    })

}`

**Comment by GeorgeAnanthSoosai** [comment]
Can you please let me know which stable version are you using ?

**Comment by adavidof** [comment]
any updates?
