### ISSUE TITLE
Cannot read property 'length' of undefined at NetMessage.size

### ISSUE THREAD

**Issue by leonerd** [zerobias/telegram-mtproto#55]
Just saw this in log:

```
REQUEST
REQUEST
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at NetMessage.size (/home/telegramas/matrix-appservice-tg/node_modules/telegram-mtproto/lib/service/networker/net-message.js:60:91)
    at NetworkerThread.performSheduledRequest (/home/telegramas/matrix-appservice-tg/node_modules/telegram-mtproto/lib/service/networker/index.js:226:41)
    at _bluebird2.default.resolve.then (/home/telegramas/matrix-appservice-tg/node_modules/mtproto-shared/lib/timeout.js:40:96)
    at tryCatcher (/home/telegramas/matrix-appservice-tg/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/telegramas/matrix-appservice-tg/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/telegramas/matrix-appservice-tg/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/telegramas/matrix-appservice-tg/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/telegramas/matrix-appservice-tg/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/telegramas/matrix-appservice-tg/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/telegramas/matrix-appservice-tg/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

(Running version 3.0.6)

**Comment by zerobias** [comment]
Will try to resolve and fix that
