### ISSUE TITLE
can you provide a working example for saving session that user doesn't need signin again?

### ISSUE THREAD

**Issue by alimahmoodvand** [zerobias/telegram-mtproto#59]

**Comment by wfjsw** [comment]
I am trying to persist the session but when I reused it I got
```
[2.993] Error 401 AUTH_KEY_UNREGISTERED 2 5
  follow-redirects options { maxRedirects: 21,
  protocol: 'http:',
  hostname: '149.154.171.5',
  port: null,
  path: '/apiw1',
  method: 'post',
  headers: { 'User-Agent': 'axios/0.16.1', 'Content-Length': 136 },
  agent: undefined,
  auth: undefined } +269ms
  telegram-mtproto:tl [int bytes]  [2.981]  e2141******18634 auth_key_id:int64 +32ms
  telegram-mtproto:tl [int bytes]  [2.981]  fddde949f96d**************002543 msg_key:int128 +0ms
  telegram-mtproto:tl [raw bytes]  [2.981]  43b2b7897578704947e8e202a5828334ae5ad5f2223bc7aed17c7b62479902b77e7c526304966ff70452b6d821fc5186cca77281516e00a9b7d55325ebc909ddb7d0eba0f51f63ad743a69 encrypted_data +0ms
  telegram-mtproto:tl [int bytes]  [2.983]  2df3******36d7cc salt:int64 +1ms
  telegram-mtproto:tl [int bytes]  [2.984]  b908******d2712d session_id:int64 +0ms
  telegram-mtproto:tl:reader [int]  [2.984]  message_id:long[low] 687022081 +0ms
  telegram-mtproto:tl:reader [int]  [2.984]  message_id:long[high] 1496739247 +0ms
  telegram-mtproto:tl:reader [int]  [2.984]  seq_no:int 5 +0ms
  telegram-mtproto:tl:reader [int]  [2.986]  message_data[length]:int 44 +0ms
  telegram-mtproto:tl [raw bytes]  [2.986]  016d5cf3a4686067ae6d365919ca44219101000015415554485f4b45595f554e524547495354455245440000 message_data +1ms
  telegram-mtproto:tl:reader [int]  [2.986]  INPUT[id] 4082920705 +0ms
  telegram-mtproto:tl:reader [int]  [2.986]  INPUT[rpc_result][req_msg_id]:long[low] 1734371492 +0ms
  telegram-mtproto:tl:reader [int]  [2.986]  INPUT[rpc_result][req_msg_id]:long[high] 1496739246 +0ms
  telegram-mtproto:tl:reader [int]  [2.986]  INPUT[rpc_result][result][id] 558156313 +0ms
  telegram-mtproto:tl:reader [int]  [2.986]  INPUT[rpc_result][result][rpc_error][error_code]:int 401 +0ms
  telegram-mtproto:tl:reader [bytes]  [2.986]  415554485f4b45595f554e52454749535445524544 INPUT[rpc_result][result][rpc_error][error_message]:string:bytes +0ms
  telegram-mtproto:tl:reader [string]  [2.987]  AUTH_KEY_UNREGISTERED INPUT[rpc_result][result][rpc_error][error_message]:string +1ms
  telegram-mtproto:networker [Server response]  [2.990]  5 { response:
   { _: 'rpc_result',
     req_msg_id: '6428446113944070308',
     result:
      { _: 'rpc_error',
        error_code: 401,
        error_message: 'AUTH_KEY_UNREGISTERED' } },
  messageID: '6428446117191688193',
  sessionID: Uint8Array [ 185, 8, 183, 65, 10, 210, 113, 45 ],
  seqNo: 5 } +0ms
  telegram-mtproto:networker [ERROR][Rpc error]  [2.990]  { Error: 401 AUTH_KEY_UNREGISTERED CODE#401 AUTH_KEY_UNREGISTERED
  telegram-mtproto:networker     at NetworkerThread.processError (/home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:573:12)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:728:34
  telegram-mtproto:networker     at Generator.next (<anonymous>)
  telegram-mtproto:networker     at step (/home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:202)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:459
  telegram-mtproto:networker     at Promise._execute (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/debuggability.js:300:9)
  telegram-mtproto:networker     at Promise._resolveFromExecutor (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:483:18)
  telegram-mtproto:networker     at new Promise (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:79:10)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:99
  telegram-mtproto:networker     at NetworkerThread.processMessage (/home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:770:7)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:336:21
  telegram-mtproto:networker     at Generator.next (<anonymous>)
  telegram-mtproto:networker     at step (/home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:202)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:383
  telegram-mtproto:networker     at tryCatcher (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/util.js:16:23)
  telegram-mtproto:networker     at Promise._settlePromiseFromHandler (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:512:31)
  telegram-mtproto:networker     at Promise._settlePromise (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:569:18)
  telegram-mtproto:networker     at Promise._settlePromise0 (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:614:10)
  telegram-mtproto:networker     at Promise._settlePromises (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:693:18)
  telegram-mtproto:networker     at Async._drainQueue (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/async.js:133:16)
  telegram-mtproto:networker     at Async._drainQueues (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/async.js:143:10)
  telegram-mtproto:networker     at Immediate.Async.drainQueues (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/async.js:17:14)
  telegram-mtproto:networker     at runCallback (timers.js:800:20)
  telegram-mtproto:networker     at tryOnImmediate (timers.js:762:5)
  telegram-mtproto:networker     at processImmediate [as _immediateCallback] (timers.js:733:5)
  telegram-mtproto:networker   code: 401,
  telegram-mtproto:networker   type: 'AUTH_KEY_UNREGISTERED',
  telegram-mtproto:networker   description: 'CODE#401 AUTH_KEY_UNREGISTERED',
  telegram-mtproto:networker   originalError:
  telegram-mtproto:networker    { _: 'rpc_error',
  telegram-mtproto:networker      error_code: 401,
  telegram-mtproto:networker      error_message: 'AUTH_KEY_UNREGISTERED' } } +2ms
  telegram-mtproto:networker [non phone error]  [2.991]  401 CODE#401 AUTH_KEY_UNREGISTERED +3ms
  telegram-mtproto:simple-file-storage [get][key dc]  [2.992]  5 +1ms
  telegram-mtproto:simple-file-storage [get][key dc]  [2.994]  5 +300ms
  telegram-mtproto:networker [Api call]  [2.996]  auth.exportAuthorization { dc_id: 5 } 6428446117390020500 7 { noErrorBox: true,
  resultType: 'auth.ExportedAuthorization',
  messageID: '6428446117390020500' } +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [2.996]  e5bfffcd 3854565325 auth.exportAuthorization[id]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [2.996]  5 5 f auth.exportAuthorization(dc_id):int +0ms
  telegram-mtproto:networker [acking messages]  [2.996]  [ '6428446117191688193' ] +0ms
  telegram-mtproto:networker [MT message]  [2.996]  6428446117390064620 { _: 'msgs_ack', msg_ids: [ '6428446117191688193' ] } 8 +0ms
  telegram-mtproto:networker [Container]  [3.001]  6428446117390020500,6428446117390064620 [] 6428446117400629636 8 +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  62d6b459 1658238041 undefined.msgs_ack[id]:int +1ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  1cb5c415 481674261 undefined.msgs_ack.msg_ids[id]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  1 1 undefined.msgs_ack.msg_ids[count]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  28f32001 687022081 undefined.msgs_ack.msg_ids[0]:long[low] +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  59366daf 1496739247 undefined.msgs_ack.msg_ids[0]:long[high] +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  73f1f8dc 1945237724 CONTAINER[id]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  2 2 CONTAINER[count]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  34c56f94 885354388 CONTAINER[0][msg_id]:long[low] +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  59366daf 1496739247 CONTAINER[0][msg_id]:long[high] +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  7 7 CONTAINER[0][seq_no]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  8 8 CONTAINER[0][bytes]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  34c61bec 885398508 CONTAINER[1][msg_id]:long[low] +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  59366daf 1496739247 CONTAINER[1][msg_id]:long[high] +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  8 8 CONTAINER[1][seq_no]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  14 20 CONTAINER[1][bytes]:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  35675184 895963524 message_id:long[low] +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  59366daf 1496739247 message_id:long[high] +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  8 8 seq_no:int +0ms
  telegram-mtproto:tl:type-buffer [writeInt]  [3.002]  44 68 message_data_length:int +0ms
[3.604] Error 401 AUTH_KEY_UNREGISTERED 2 5
  telegram-mtproto:tl [int bytes]  [3.595]  e2141*******8634 auth_key_id:int64 +301ms
  telegram-mtproto:tl [int bytes]  [3.596]  fba806da************c9e06b0c1205 msg_key:int128 +1ms
  telegram-mtproto:tl [raw bytes]  [3.596]  3c1a6ed45eccb8ff13ba48541965949810d8f98e1b2ef991066abb932cf0d317694029c05cc06deda654000a9d32896d81a27a4c50abe54ed702cc3480185340bff351ece63122ce27d917 encrypted_data +0ms
  telegram-mtproto:tl [int bytes]  [3.599]  2df36******6d7cc salt:int64 +0ms
  telegram-mtproto:tl [int bytes]  [3.599]  b908b******2712d session_id:int64 +0ms
  telegram-mtproto:tl:reader [int]  [3.599]  message_id:long[low] 3324217345 +0ms
  telegram-mtproto:tl:reader [int]  [3.599]  message_id:long[high] 1496739247 +0ms
  telegram-mtproto:tl:reader [int]  [3.599]  seq_no:int 7 +1ms
  telegram-mtproto:tl:reader [int]  [3.599]  message_data[length]:int 44 +0ms
  telegram-mtproto:tl [raw bytes]  [3.600]  016d5cf3946fc534af6d365919ca44219101000015415554485f4b45595f554e524547495354455245440000 message_data +0ms
  telegram-mtproto:tl:reader [int]  [3.600]  INPUT[id] 4082920705 +0ms
  telegram-mtproto:tl:reader [int]  [3.601]  INPUT[rpc_result][req_msg_id]:long[low] 885354388 +0ms
  telegram-mtproto:tl:reader [int]  [3.601]  INPUT[rpc_result][req_msg_id]:long[high] 1496739247 +0ms
  telegram-mtproto:tl:reader [int]  [3.601]  INPUT[rpc_result][result][id] 558156313 +0ms
  telegram-mtproto:tl:reader [int]  [3.601]  INPUT[rpc_result][result][rpc_error][error_code]:int 401 +1ms
  telegram-mtproto:tl:reader [bytes]  [3.601]  415554485f4b45595f554e52454749535445524544 INPUT[rpc_result][result][rpc_error][error_message]:string:bytes +0ms
  telegram-mtproto:tl:reader [string]  [3.602]  AUTH_KEY_UNREGISTERED INPUT[rpc_result][result][rpc_error][error_message]:string +0ms
  telegram-mtproto:networker [Server response]  [3.603]  5 { response:
   { _: 'rpc_result',
     req_msg_id: '6428446117390020500',
     result:
      { _: 'rpc_error',
        error_code: 401,
        error_message: 'AUTH_KEY_UNREGISTERED' } },
  messageID: '6428446119828883457',
  sessionID: Uint8Array [ 185, 8, 183, 65, 10, 210, 113, 45 ],
  seqNo: 7 } +0ms
  telegram-mtproto:networker [ERROR][Rpc error]  [3.603]  { Error: 401 AUTH_KEY_UNREGISTERED CODE#401 AUTH_KEY_UNREGISTERED
  telegram-mtproto:networker     at NetworkerThread.processError (/home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:573:12)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:728:34
  telegram-mtproto:networker     at Generator.next (<anonymous>)
  telegram-mtproto:networker     at step (/home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:202)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:459
  telegram-mtproto:networker     at Promise._execute (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/debuggability.js:300:9)
  telegram-mtproto:networker     at Promise._resolveFromExecutor (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:483:18)
  telegram-mtproto:networker     at new Promise (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:79:10)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:99
  telegram-mtproto:networker     at NetworkerThread.processMessage (/home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:770:7)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:336:21
  telegram-mtproto:networker     at Generator.next (<anonymous>)
  telegram-mtproto:networker     at step (/home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:202)
  telegram-mtproto:networker     at /home/brainbush/wfjsw/telegram-mtproto/lib/service/networker/index.js:76:383
  telegram-mtproto:networker     at tryCatcher (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/util.js:16:23)
  telegram-mtproto:networker     at Promise._settlePromiseFromHandler (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:512:31)
  telegram-mtproto:networker     at Promise._settlePromise (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:569:18)
  telegram-mtproto:networker     at Promise._settlePromise0 (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:614:10)
  telegram-mtproto:networker     at Promise._settlePromises (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/promise.js:693:18)
  telegram-mtproto:networker     at Async._drainQueue (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/async.js:133:16)
  telegram-mtproto:networker     at Async._drainQueues (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/async.js:143:10)
  telegram-mtproto:networker     at Immediate.Async.drainQueues (/home/brainbush/wfjsw/telegram-mtproto/node_modules/bluebird/js/release/async.js:17:14)
  telegram-mtproto:networker     at runCallback (timers.js:800:20)
  telegram-mtproto:networker     at tryOnImmediate (timers.js:762:5)
  telegram-mtproto:networker     at processImmediate [as _immediateCallback] (timers.js:733:5)
  telegram-mtproto:networker   code: 401,
  telegram-mtproto:networker   type: 'AUTH_KEY_UNREGISTERED',
  telegram-mtproto:networker   description: 'CODE#401 AUTH_KEY_UNREGISTERED',
  telegram-mtproto:networker   originalError:
  telegram-mtproto:networker    { _: 'rpc_error',
  telegram-mtproto:networker      error_code: 401,
  telegram-mtproto:networker      error_message: 'AUTH_KEY_UNREGISTERED' } } +2ms
  telegram-mtproto:networker [non phone error]  [3.603]  401 CODE#401 AUTH_KEY_UNREGISTERED +3ms
```

Code: 
```
'use strict';

var mtp = require('/path/to/telegram-mtproto/lib').MTProto
var storeng = require('/path/to/telegram-mtproto/lib/plugins/file-storage').FileStorage
const api = {
    layer: 57,
    initConnection: 0x69796de9,
    api_id: 24275,
    app_version: '1.0.0',
    lang_code: 'en'
}
const server = {
    dev: false,
    webogram: false
}

function Bot (config) {
    var app= {
        storage: new storeng('../useraccount', JSON.parse(require('fs').readFileSync('../useraccount')))
    }
    var cli = mtp({server, app, api})
    cli('account.getAuthorizations', {}).then(console.log)
}

module.exports = Bot
```

**Comment by ali-mahmoodvand** [comment]
@zerobias please help us :)

**Comment by zerobias** [comment]
@wfjsw Which version did you use?
Also, it may be worth checking whether the data have been restored with exactly same type

**Comment by wfjsw** [comment]
@zerobias checked.
I am using `feature/mtproto3` directly

**Comment by ali-mahmoodvand** [comment]
@zerobias beta version

**Comment by zerobias** [comment]
@ali-mahmoodvand `@alpha` branch is better at this time

**Comment by zerobias** [comment]
@wfjsw will try to reproduce that now

Perhaps, you had been assigned to another dc rather than what is stored in memory and error is thrown when the library is trying to switch between them.

**Comment by ali-mahmoodvand** [comment]
@zerobias ,@wfjsw  
i solve this problem with 3.0.5-unstable version


const { MTProto } =  require('telegram-mtproto');
const { Storage } = require('mtproto-storage-fs')
const api = {
  invokeWithLayer: 0xda9b0d0d,
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : *******,
  app_version    : '1.0.1',
  lang_code      : 'en'
}
const app = {
  storage: new Storage('./storage.json')
 }
const server = { webogram: true, dev: false }

const telegram = MTProto({ api, server ,app})

module.exports = telegram


after that i login and save session 
const telegram = require('./init')

const { inputField } = require('./fixtures')
const config = {
  // NOTE: if you FORK the project you MUST use your APP ID.
  // Otherwise YOUR APPLICATION WILL BE BLOCKED BY TELEGRAM
  // You can obtain your own APP ID for your application here: https://my.telegram.org
  id  : ******,
  hash: '******************************************'
}

const login = async () => {
  try {
    // const phone = await inputField('phone')
    // console.log(phone)
   await telegram.storage.clear()
    const phone = '******************************'
    const { phone_code_hash } = await telegram('auth.sendCode', {
            phone_number  : phone,
            current_number: true,
            api_id        : config.id,
            api_hash      : config.hash
    })
     const code = await inputField('code')
   // const code = '22222'
    const res = await telegram('auth.signIn', {
      phone_number: phone,
      phone_code_hash,
      phone_code  : code
    })
    await telegram.storage.save()
    const { user } = res
    const {
      first_name = '',
      username = ''
    } = user
    console.log('signIn', first_name, username, user.phone)
    return first_name
  } catch (error) {
    console.error(error)
  }
}

module.exports = login

for next time i just init telegram module without login and this work fine :)

**Comment by wfjsw** [comment]
@ali-mahmoodvand use preformatted code block for codes plz
@zerobias I have examined the log carefully but I can't see any dc change (it is 5 now)
Full log is available if needed.

**Comment by wfjsw** [comment]
@ali-mahmoodvand BTW, have you executed any real API function and have the log examined after session loaded?

**Comment by zerobias** [comment]
@wfjsw Oh, that is useful, I will look at 2FA

**Comment by wfjsw** [comment]
https://gist.github.com/wfjsw/db29183ddd3f5bfac99c5bb25c1117c8

**Comment by wfjsw** [comment]
Is the lib holding somethings else important in memory?
I ran every example individually and got the exact same error.

**Comment by wfjsw** [comment]
Had a casual look at the logs and noticed the lib is generating a new dh pair every start up.

**Comment by Lord-Protector** [comment]
@wfjsw you should write your own storage interface for storing some nessesary variables. #27

**Comment by wfjsw** [comment]
@Lord-Protector I am using a stock file-storage for that ATM.

**Comment by zerobias** [comment]
@wfjsw Yes, noticed that too. Now I'm working on more predictable auth

**Comment by zerobias** [comment]
@wfjsw As for storages, `simple-` was not stable enough. Current file storage implementation is `mtproto-storage-fs` (reactive)

**Comment by wfjsw** [comment]
@zerobias I have experienced a 404 when requiring mtproto-storage-fs.
Have inspected node_modules and found the storage lib was not built (no lib, no es, only src was there)

**Comment by elyas74** [comment]
@wfjsw 
same issue here!

**Comment by zerobias** [comment]
@wfjsw Found a problem in the build process. Can you check if this problem is solved in `mtproto-storage-fs@0.1.7`?

**Comment by wfjsw** [comment]
@zerobias Have no time in 2 weeks, I am afraid.

**Comment by wfjsw** [comment]
Currently it says `Cannot find module 'mtproto-shared'`

**Comment by wfjsw** [comment]
@zerobias same issue for mtproto-shared.

**Comment by zerobias** [comment]
Mtproto now has separate test for proving that saving session is works

It works when you use same storage data in separate instances; just load next instance and continue to work

https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/test/node.test.js#L139

**Comment by dundas** [comment]
Still struggling with this library. Would anyone be willing to help me get this set up for log in, get phone code, and send message. Would be willing to send a $25 amazon or starbucks card  :). Let me know thanks!
