### ISSUE TITLE
Best way to retrieve error response

### ISSUE THREAD

**Issue by incubus** [zerobias/telegram-mtproto#65]
Hi!

 `telegram-mtproto@3.1.0`

  Is there any way to retrieve error response ```{ _: 'rpc_error', error_code: 400, error_message: 'USERNAME_NOT_OCCUPIED' }``` except patching `_asyncToGenerator` method in `index.js`?

 Thanks!

**Comment by wfjsw** [comment]
Promise catch?

**Comment by incubus** [comment]
I've tried this:

```
await new Promise((resolve, reject) => {
        const result = telegram('auth.sendCode', params);
        resolve(result);
      }).catch((err) => {
        console.log(err);
      }).then((result) => {
        callback(result);
      });
```

**Comment by wfjsw** [comment]
When you use await you should also use try...catch block I think

**Comment by incubus** [comment]
Yep, full example:

```
    try {
      await new Promise((resolve, reject) => {
        const result = telegram('auth.sendCode', params);
        resolve(result);
      }).catch((err) => {
        console.log(err);
      }).then((result) => {
        callback(result);
      });
    } catch (err) {
      console.log(err);
    }
```

**Comment by wfjsw** [comment]
I am just wondering why you use await along with Promise catch & then

**Comment by incubus** [comment]
My bad. But it still doesnt'work

```
      new Promise((resolve, reject) => {
        resolve(telegram('auth.sendCode', params));
      }).catch((err) => {
        console.log(err);
      }).then((result) => {
        console.log(result);
      });
```

Have you tried? :)

**Comment by goodmind** [comment]
What version are you using?

**Comment by incubus** [comment]
telegram-mtproto@3.1.0

**Comment by wfjsw** [comment]
```
telegram('auth.sendCode', params)
      .catch((err) => {
        console.log(err);
      }).then((result) => {
        console.log(result);
      });
```
telegram-mtproto supports Promise natively :\

**Comment by incubus** [comment]
Unfortunately it doesn't work with 3.1.0 version.

**Comment by incubus** [comment]
Here is the output for simple code:
```
      telegram('contacts.resolveUsername', {username: 'tefdsfsdfdsst'})
        .catch((err) => {
          console.log('Got it!');
          console.log(err);
        }).then((result) => {
          console.log(result);
        });
```

```
(node:92244) Warning: a promise was rejected with a non-error: [object Object]
[7.469] Error undefined undefined 2 2
Trace: Unhandled performRequest
    at /Users/incubus/workspace/server/node_modules/telegram-mtproto/src/service/api-manager/index.js:266:15
    at Generator.throw (<anonymous>)
    at step (/Users/incubus/workspace/server/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:202)
    at /Users/incubus/workspace/server/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:424
    at tryCatcher (/Users/incubus/workspace/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/incubus/workspace/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/incubus/workspace/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/incubus/workspace/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/incubus/workspace/server/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/incubus/workspace/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/incubus/workspace/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/incubus/workspace/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
[rejectPromise] Unhandled error! { _: 'rpc_error',
  error_code: 400,
  error_message: 'USERNAME_NOT_OCCUPIED' }
(node:92244) Warning: a promise was rejected with a non-error: [object Object]
Unhandled rejection (<{"_":"rpc_error","error_code":400,"err...>, no stack trace)
```

**Comment by goodmind** [comment]
Promises are broken in 3.1.0 (well, actually they're fixed, because `catch` don't worked in 3.0.5)

**Comment by incubus** [comment]
Ah, I see. Thanks!

**Comment by goodmind** [comment]
Will be fixed soon I think
