### ISSUE TITLE
error at signIn method

### ISSUE THREAD

**Issue by Alavi1412** [zerobias/telegram-mtproto#75]
when I use this code:
```

const { phone_code_hash } = await client('auth.sendCode', {
        phone_number  : phone,
        current_number: false,
        api_id        : api.id,
        api_hash      : 'api.hash'
    });

    const code = await inputField('code');

    const { user } = await client('auth.signIn', {
        phone_number   : phone,
        phone_code_hash: phone_code_hash,
        phone_code     : code
    });

```
I got the following error. how can I bypass this error?

```
Unhandled rejection Error: Constructor not found: 773059779 1111 949189
Encrypted request failed Error: Constructor not found: 773059779 1111 949189
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:442:15)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:442:15)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:478:26)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:478:26)
    at Deserialization.mt_rpc_result (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:1117:28)
    at Deserialization.mt_rpc_result (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:1117:28)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:452:34)
    at /home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:419:39
    at Generator.next (<anonymous>)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:452:34)
    at step (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
    at /home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:419:39
    at /home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
    at Generator.next (<anonymous>)
    at tryCatcher (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:512:31)
    at step (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
    at Promise._settlePromise (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:569:18)
    at /home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
    at Promise._settlePromise0 (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:614:10)
    at tryCatcher (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromises (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._settlePromiseFromHandler (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:512:31)
    at Async._drainQueue (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:133:16)
    at Promise._settlePromise (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:569:18)
    at Async._drainQueues (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:143:10)
    at Promise._settlePromise0 (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:614:10)
    at Immediate.Async.drainQueues (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:17:14)
    at Promise._settlePromises (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:17:14)
Encrypted request failed Error: Constructor not found: 773059779 1111 949189
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:442:15)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:478:26)
    at Deserialization.mt_rpc_result (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:1117:28)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:452:34)
    at /home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:419:39
    at Generator.next (<anonymous>)
    at step (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
    at /home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
    at tryCatcher (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:17:14)
Unhandled rejection Error: Constructor not found: 773059779 1111 949189
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:442:15)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:478:26)
    at Deserialization.mt_rpc_result (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:1117:28)
    at Deserialization.fetchObject (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/tl/index.js:452:34)
    at /home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:419:39
    at Generator.next (<anonymous>)
    at step (/home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
    at /home/alavi/WebstormProjects/viewer_bot/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
    at tryCatcher (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/alavi/WebstormProjects/viewer_bot/node_modules/bluebird/js/release/async.js:17:14)
Unhandled rejection undefined
```

**Comment by goodmind** [comment]
What version are you using?

**Comment by goodmind** [comment]
@Alavi1412 why you closed this?
