### ISSUE TITLE
Error: Actions must be plain objects. Use custom middleware for async actions.

### ISSUE THREAD

**Issue by irudoy** [zerobias/telegram-mtproto#78]
```
Error: Actions must be plain objects. Use custom middleware for async actions.
    at dispatch (/.../source/node_modules/redux/lib/createStore.js:165:13)
    at /.../source/node_modules/redux-most/lib/createEpicMiddleware.js:40:22
    at action (/.../source/node_modules/telegram-mtproto/lib/state/middleware.js:21:110)
    at dispatch (/.../source/node_modules/redux/lib/applyMiddleware.js:45:18)
    at TapSink.event (/.../source/node_modules/most/lib/combinator/transform.js:80:3)
    at Segment.event (/.../source/node_modules/most/lib/combinator/switch.js:113:15)
    at MergeSink.event (/.../source/node_modules/most/lib/combinator/merge.js:110:13)
    at IndexSink.event (/.../source/node_modules/most/lib/sink/IndexSink.js:28:13)
    at SafeSink.event (/.../source/node_modules/most/lib/sink/SafeSink.js:20:13)
    at Object.tryEvent (/.../source/node_modules/most/lib/source/tryEvent.js:14:10)
    at RecoverWithSink.event (/.../source/node_modules/most/lib/combinator/errors.js:87:12)
    at MapSink.event (/.../source/node_modules/most/lib/fusion/Map.js:71:13)
    at AwaitSink._eventBound (/.../source/node_modules/most/lib/combinator/promises.js:63:15)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by zerobias** [comment]
Issue is most likely solved in recent mtproto3 commits; needs confirmation

**Comment by irudoy** [comment]
If the error appears again, I'll reopen it
