### ISSUE TITLE
Telegram session termination error

### ISSUE THREAD

**Issue by nikhiljohn10** [zerobias/telegram-mtproto#81]
Hi there,

I need help with following code.
```
try {
	return (await telegram('auth.logOut', {}));
} catch (error) {
	console.error(error);
}
```
I am receiving the following error when logging out from telegram session. The same error is received from server to the terminal when session is terminated from web.telegram.org/test=1

This is done is both express js and sails js. But both are giving same error.

```
Encrypted request failed { Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.167.40/apiw1
    at NetworkerThread._ref20 (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:1050:40)
    at _ref20.throw (<anonymous>)
    at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
    at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:424
From previous event:
    at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:359)
    at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
  code: 406,
  type: 'NETWORK_BAD_REQUEST',
  originalError: 
   { Error: socket hang up
       at createHangUpError (_http_client.js:345:15)
       at Socket.socketOnEnd (_http_client.js:437:23)
       at emitNone (events.js:110:20)
       at Socket.emit (events.js:207:7)
       at endReadableNT (_stream_readable.js:1059:12)
       at _combinedTickCallback (internal/process/next_tick.js:138:11)
       at process._tickDomainCallback (internal/process/next_tick.js:218:9)
   From previous event:
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:344)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
   From previous event:
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:359)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:459
   From previous event:
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:99
       at _bluebird2.default.resolve.then (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/util/smart-timeout.js:39:94)
   From previous event:
       at exports.immediate.args (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/util/smart-timeout.js:39:83)
       at NetworkerThread.sheduleRequest (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:447:139)
       at NetworkerThread.pushMessage (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:239:46)
       at NetworkerThread.wrapMtpCall (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:184:10)
       at NetworkerThread.<anonymous> (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:745:18)
       at Generator.next (<anonymous>)
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:459
   From previous event:
       at NetworkerThread.sendLongPoll (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:99)
       at NetworkerThread.<anonymous> (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:738:19)
       at Generator.next (<anonymous>)
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
       at runCallback (timers.js:781:20)
       at tryOnImmediate (timers.js:743:5)
       at processImmediate [as _immediateCallback] (timers.js:714:5)
     code: 'ECONNRESET',
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        responseType: 'arraybuffer',
        url: 'http://149.154.167.40/apiw1',
        data: ArrayBuffer { byteLength: 232 } },
     response: undefined } }
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
(node:3230) Warning: a promise was rejected with a non-error: [object Undefined]
Unhandled rejection Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.167.40/apiw1
    at NetworkerThread._ref20 (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:1050:40)
    at _ref20.throw (<anonymous>)
    at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
    at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:424
From previous event:
    at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:359)
    at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

Unhandled rejection undefined

Unhandled rejection undefined

Unhandled rejection undefined

Unhandled rejection undefined

Unhandled rejection undefined

Encrypted request failed { Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.167.40/apiw1
    at NetworkerThread._ref20 (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:1050:40)
    at _ref20.throw (<anonymous>)
    at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
    at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:424
From previous event:
    at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:359)
    at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
  code: 406,
  type: 'NETWORK_BAD_REQUEST',
  originalError: 
   { Error: socket hang up
       at createHangUpError (_http_client.js:345:15)
       at Socket.socketOnEnd (_http_client.js:437:23)
       at emitNone (events.js:110:20)
       at Socket.emit (events.js:207:7)
       at endReadableNT (_stream_readable.js:1059:12)
       at _combinedTickCallback (internal/process/next_tick.js:138:11)
       at process._tickDomainCallback (internal/process/next_tick.js:218:9)
   From previous event:
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:344)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
   From previous event:
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:359)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:459
   From previous event:
       at NetworkerThread.<anonymous> (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:99)
       at NetworkerThread.sendEncryptedRequest (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:1058:21)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:938:33
       at Generator.next (<anonymous>)
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:459
   From previous event:
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:99
       at _bluebird2.default.resolve.then (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/util/smart-timeout.js:39:94)
   From previous event:
       at exports.immediate.args (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/util/smart-timeout.js:39:83)
       at NetworkerThread.sheduleRequest (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:447:139)
       at NetworkerThread.pushMessage (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:239:46)
       at NetworkerThread.wrapApiCall (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:230:10)
       at Request.requestWith.networker (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/request.js:37:47)
   From previous event:
       at Request.performRequest (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/request.js:35:54)
       at ApiManager._ref6 (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/index.js:203:11)
       at _ref6.next (<anonymous>)
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/index.js:70:202)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/index.js:70:383
       at runCallback (timers.js:781:20)
       at tryOnImmediate (timers.js:743:5)
       at processImmediate [as _immediateCallback] (timers.js:714:5)
   From previous event:
       at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/index.js:70:359)
       at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/index.js:70:459
   From previous event:
       at ApiManager.<anonymous> (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/index.js:70:99)
       at ApiManager.mtpInvokeApi (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/api-manager/index.js:219:22)
       at Object.logout (/Users/nikzjon/work/node/t-auth/api/services/AuthService.js:56:18)
       at Object.wrapper [as logout] (/usr/local/lib/node_modules/sails/node_modules/@sailshq/lodash/lib/index.js:3250:19)
       at Object.logout (/Users/nikzjon/work/node/t-auth/api/controllers/AuthController.js:127:8)
       at wrapper (/usr/local/lib/node_modules/sails/node_modules/@sailshq/lodash/lib/index.js:3250:19)
       at routeTargetFnWrapper (/usr/local/lib/node_modules/sails/lib/router/bind.js:181:5)
       at callbacks (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:164:37)
       at param (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:138:11)
       at pass (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:145:5)
       at nextRoute (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:100:7)
       at callbacks (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:167:11)
       at alwaysAllow (/usr/local/lib/node_modules/sails/lib/hooks/policies/index.js:224:11)
       at routeTargetFnWrapper (/usr/local/lib/node_modules/sails/lib/router/bind.js:181:5)
       at callbacks (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:164:37)
       at param (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:138:11)
       at pass (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:145:5)
       at nextRoute (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:100:7)
       at callbacks (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:167:11)
       at module.exports (/usr/local/lib/node_modules/sails/lib/hooks/cors/clear-headers.js:14:3)
       at routeTargetFnWrapper (/usr/local/lib/node_modules/sails/lib/router/bind.js:181:5)
       at callbacks (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:164:37)
       at param (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:138:11)
       at pass (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:145:5)
       at nextRoute (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:100:7)
       at callbacks (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:167:11)
       at sails.router.bind._middlewareType (/usr/local/lib/node_modules/sails/lib/hooks/csrf/index.js:148:11)
       at routeTargetFnWrapper (/usr/local/lib/node_modules/sails/lib/router/bind.js:181:5)
       at callbacks (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:164:37)
       at param (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:138:11)
       at pass (/usr/local/lib/node_modules/sails/node_modules/@sailshq/express/lib/router/index.js:145:5)
     code: 'ECONNRESET',
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        responseType: 'arraybuffer',
        url: 'http://149.154.167.40/apiw1',
        data: ArrayBuffer { byteLength: 120 } },
     response: undefined } }
Unhandled rejection Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.167.40/apiw1
    at NetworkerThread._ref20 (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:1050:40)
    at _ref20.throw (<anonymous>)
    at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:202)
    at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:424
From previous event:
    at step (/Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:359)
    at /Users/nikzjon/work/node/t-auth/node_modules/telegram-mtproto/lib/service/networker/index.js:62:383
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by nikhiljohn10** [comment]
### Solved by upgrading to telegram-mtproto 3.0.6

`npm install telegram-mtproto@3.0.6 --save`
