### ISSUE TITLE
NETWORK_BAD_REQUEST during auth.sendCode request

### ISSUE THREAD

**Issue by dmitrdv** [zerobias/telegram-mtproto#86]
Hi!

I got following error during sending auth.sendCode request:

>   code: 406,
>   type: 'NETWORK_BAD_REQUEST',
>   originalError:
>    { Error: Request failed with status code 404
>        at createError (c:\Users\home\workspace\test\node_modules\axios\lib\core\createError.js:15:15)
>        at settle (c:\Users\home\workspace\test\node_modules\axios\lib\core\settle.js:18:12)
>        at IncomingMessage.handleStreamEnd (c:\Users\home\workspace\test\node_modules\axios\lib\adapters\http.js:186:11)
>        at emitNone (events.js:110:20)
>        at IncomingMessage.emit (events.js:207:7)
>        at endReadableNT (_stream_readable.js:1047:12)
>        at _combinedTickCallback (internal/process/next_tick.js:102:11)
>        at process._tickCallback (internal/process/next_tick.js:161:9)
>      config:
>       { adapter: [Function: httpAdapter],
>         transformRequest: [Object],
>         transformResponse: [Object],
>         timeout: 0,
>         xsrfCookieName: 'XSRF-TOKEN',
>         xsrfHeaderName: 'X-XSRF-TOKEN',
>         maxContentLength: -1,
>         validateStatus: [Function: validateStatus],
>         headers: [Object],
>         method: 'post',
>         responseType: 'arraybuffer',
>         url: 'http://149.154.167.51/apiw1',
>         data: ArrayBuffer { byteLength: 184 } },
>      response:
>       { status: 404,
>         statusText: 'Not Found',
>         headers: [Object],
>         config: [Object],
>         request: [Object],
>         data: <Buffer 3c 68 74 6d 6c 3e 0d 0a 3c 68 65 61 64 3e 3c 74 69 74 6c 65 3e 34 30 34 20 4e 6f 74 20 46 6f 75 6e 64 3c 2f 74 69 74 6c 65 3e 3c 2f 68 65 61 64 3e 0d ... > } } }

I am using:
```
"mtproto-storage-fs": "^0.3.0"
"telegram-mtproto": "^3.0.6"
```

Code is following:
```
const { MTProto } = require('telegram-mtproto')
const { Storage } = require('mtproto-storage-fs')
const { inputField } = require('./fixtures')

const phone_number ='+************'

const server = {
  dev: false
}

const api = {
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : 49631
}

const app = {
  storage: new Storage('./storage')
}

const client = MTProto({ server, api, app })

async function connect() {
  const { phone_code_hash } = await client('auth.sendCode', {
    phone_number  : phone_number,
    current_number: false,
    api_id        : 49631,
    api_hash      : 'fb050b8f6771e15bfda5df2409931569'
  })
  
  const code = await inputField('code')

  const { user } = await client('auth.signIn', {
    phone_number   : phone_number,
    phone_code_hash: phone_code_hash,
    phone_code     : code
  })

  console.log('signed as ', user)
}

connect()
```

**Comment by dmitrdv** [comment]
[1.txt](https://github.com/zerobias/telegram-mtproto/files/1290541/1.txt)
[index.txt](https://github.com/zerobias/telegram-mtproto/files/1290542/index.txt)

**Comment by dmitrdv** [comment]
when I changed api id and api hash to my the all start to works fine
