### ISSUE TITLE
TypeError: Unable to get property 'resolved' of undefined or null reference

### ISSUE THREAD

**Issue by wfjsw** [zerobias/telegram-mtproto#96]
```
--- request error ---
 { _: 'rpc_error',
  error_code: 303,
  error_message: 'USER_MIGRATE_5' }
/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/reducer/progress.js:91
var onlyAPI = units => units.filter(p => p.flags.api && p.api.resolved);
                                         ^

TypeError: Unable to get property 'resolved' of undefined or null reference
   at Anonymous function (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/reducer/progress.js:91:42)
   at Array.prototype.filter (native code)
   at onlyAPI (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/reducer/progress.js:91:24)
   at [] (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/reducer/progress.js:67:5)
   at reduce (/home/wfjsw/nojvbao-rpc/node_modules/redux-act/lib/createReducer.js:90:9)
   at combination (/home/wfjsw/nojvbao-rpc/node_modules/redux/lib/combineReducers.js:133:7)
   at watcher (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/reducer/progress.js:130:3)
   at combination (/home/wfjsw/nojvbao-rpc/node_modules/redux/lib/combineReducers.js:133:7)
   at decoratedClient (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/reducer/index.js:175:3)
   at clientReducer (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/reducer/index.js:188:3)
   at combination (/home/wfjsw/nojvbao-rpc/node_modules/redux/lib/combineReducers.js:133:7)
   at dispatch (/home/wfjsw/nojvbao-rpc/node_modules/redux/lib/createStore.js:178:7)
   at Anonymous function (/home/wfjsw/nojvbao-rpc/node_modules/redux-most/lib/createEpicMiddleware.js:46:9)
   at Anonymous function (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/middleware.js:28:39)
   at Anonymous function (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/middleware.js:21:53)
   at Anonymous function (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/middleware.js:21:39)
   at Anonymous function (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/middleware.js:43:87)
   at EventEmitter.prototype.emit (/home/wfjsw/nojvbao-rpc/node_modules/eventemitter2/lib/eventemitter2.js:382:11)
   at dispatch (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/portal.js:38:3)
   at Anonymous function (/home/wfjsw/nojvbao-rpc/node_modules/telegram-mtproto/lib/state/epic/task.js:176:4)
   at resolved (/home/wfjsw/nojvbao-rpc/node_modules/fluture/index.js:684:57)
   at resolved (/home/wfjsw/nojvbao-rpc/node_modules/fluture/index.js:175:5)
   at _fork (/home/wfjsw/nojvbao-rpc/node_modules/fluture/index.js:572:3)
   at drain (/home/wfjsw/nojvbao-rpc/node_modules/fluture/index.js:235:9)
   at settle (/home/wfjsw/nojvbao-rpc/node_modules/fluture/index.js:161:17)
```

**Comment by zerobias** [comment]
This part of the library turned out to be rather complicated, I now rewrite it in a more reliable form

**Comment by wfjsw** [comment]
By the way there is something that I'm not sure enough to open a new issue at the moment:
I noticed a memory leak when I was calling to fetch chat participants
Related code: 
```
const cache = new Set()
async function updateCache() {
    cache.clear()
    for (let group of group_to_test) {
        let {
            count,
            participants
        } = await client('channels.getParticipants', {
            channel: group,
            filter: {
                '_': 'channelParticipantsRecent'
            },
            offset: 0,
            limit: 100
        })
        for (let user of participants) {
            if (user._ == 'channelParticipant')
                cache.add(user.user_id)
        }
        if (count <= 100)
            continue
        else {
            for (let offset = 100; offset < count; offset += 100) {
                let {
                    count,
                    participants
                } = await client('channels.getParticipants', {
                    channel: group,
                    filter: {
                        '_': 'channelParticipantsRecent'
                    },
                    offset,
                    limit: 100
                })
                for (let user of participants) {
                    if (user._ == 'channelParticipant')
                        cache.add(user.user_id)
                }
            }
        }
    }
    console.log('cache size: ', cache.size)
    last_updated = new Date().valueOf()
    return cache.size
}
```

Memory goes up a little bit every time I try to update it and won't fall until I call `gc()`.

**Comment by zerobias** [comment]
@wfjsw Strong leak? :(
Some parts of the state needs to be garbage-collected manually, its highly related with issue title and will be fixed simultaneously

**Comment by zerobias** [comment]
@wfjsw Strong leak? :(
Some parts of the state needs to be garbage-collected manually, its highly related with issue title and will be fixed simultaneously

**Comment by wfjsw** [comment]
It takes 5 runs for memory usage from 5% to 22% :/

**Comment by zerobias** [comment]
Oh
I'll try to fix that in nearest release

**Comment by wfjsw** [comment]
Is there any temporary workaround to the memory leak?

**Comment by zerobias** [comment]
@wfjsw yes, you can manually clear redux store.
Its pretty huge https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/src/state/index.h.js#L92 so be careful

**Comment by goodmind** [comment]
@zerobias any news on this?
